version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3-node
      - image: circleci/redis:3.2

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install yarn
          command: sudo apt-get update && sudo apt-get install yarn

      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install Yarn dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Run tests
          command: yarn test --no-watch

      - store_artifacts:
          path: test-reports
          destination: test-reports


      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: Install Python dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"

      - run:
          name: Run Python tests
          command: |
            . venv/bin/activate
            yarn build
            pytest tests
